baseURL = "https://www.suriar.net/"
defaultcontentlanguage = "en"
languageCode = "en"
paginate = 20
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "solarized-dark"
theme = "coder"
title = "Murali's Musings"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "post"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"


[params]
  author = "Murali Suriar"
  description = "Murali Suriar's personal website"
  since = 2009

[[params.social]]
    name = "Github"
    icon = "fa fa-2x fa-github"
    weight = 1
    url = "https://github.com/msuriar/"

[[params.social]]
    name = "Twitter"
    icon = "fa fa-2x fa-twitter"
    weight = 2
    url = "https://twitter.com/msuriar/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-2x fa-linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/msuriar/"

[[params.social]]
  name = "RSS"
  icon = "fa fa-2x fa-rss"
  weight = 4
  url = "https://suriar.net/index.xml"
  rel = "alternate"
  type = "application/rss+xml"

[permalinks]
  post = "/:year/:month/:title"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"
